"""Shared constants for the yt_diarizer package."""

ENV_STAGE_VAR = "YT_DIARIZER_STAGE"
ENV_WORKDIR_VAR = "YT_DIARIZER_WORK_DIR"
ENV_URL_VAR = "YT_DIARIZER_URL"
ENV_MPS_CONVERT_VAR = "YT_DIARIZER_MPS_CONVERT"
TOKEN_FILENAME = "token.txt"
